"""empty message

Revision ID: 85446a950a6b
Revises: None
Create Date: 2016-09-25 04:21:48.822419

"""

# revision identifiers, used by Alembic.
revision = '85446a950a6b'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buku',
    sa.Column('idbuku', sa.Integer(), nullable=False),
    sa.Column('judul_buku', sa.String(length=100), nullable=True),
    sa.Column('penulis_buku', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idbuku')
    )
    op.create_table('transaksi',
    sa.Column('idtransaksi', sa.Integer(), nullable=False),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.Column('idbuku', sa.Integer(), nullable=True),
    sa.Column('tglpinjam', sa.DateTime(), nullable=True),
    sa.Column('durasi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('idtransaksi')
    )
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=54), autoincrement=False, nullable=True),
    sa.Column('time_registered', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'users_pkey'),
    sa.UniqueConstraint('email', name=u'users_email_key'),
    sa.UniqueConstraint('username', name=u'users_username_key')
    )
    op.drop_table('transaksi')
    op.drop_table('buku')
    ### end Alembic commands ###
